export const DEFAULT_RESTAURANT = {
  name: 'Saffron Table',
  tagline: 'Award-Winning Fine Dining Since 1998',
  subtitle: 'Where tradition meets culinary artistry. Experience flavors that tell a story.',
  cuisine: 'Contemporary Indian & Mediterranean Fusion',
  description:
    'Nestled in the heart of the city, Saffron Table has been serving unforgettable dining experiences for over two decades. Our chefs blend traditional recipes with modern techniques, using only the finest locally-sourced ingredients.',
  famousReason: 'Michelin-recommended fusion cuisine & legendary hospitality',
  phone: '+1 (234) 567-8900',
  email: 'info@saffrontable.com',
  address: '42 Culinary Avenue, Downtown District, NY 10001',
  hours: 'Mon–Sun: 11:00 AM – 11:00 PM',
  chef: 'Chef Rajiv Mehta',
  rating: 4.9,
  years: 25,
  tableCount: 20,
  chefs: [
    {
      name: 'Chef Rajiv Mehta',
      role: 'Executive Chef',
      experience: '22 years',
      specialty: 'Modern Indian & Mughlai Cuisine',
      ability: 'Masters complex spice blending and slow-cooking techniques with unmatched precision.',
      photo: 'https://images.unsplash.com/photo-1583394293214-e6e1e52a5904?auto=format&fit=crop&w=600&q=80',
    },
    {
      name: 'Chef Aria Patel',
      role: 'Pastry Chef',
      experience: '14 years',
      specialty: 'Fusion Desserts & Artisan Breads',
      ability: 'Transforms traditional Indian sweets into Michelin-worthy plated desserts.',
      photo: 'https://images.unsplash.com/photo-1607631568010-a87245c0daf8?auto=format&fit=crop&w=600&q=80',
    },
    {
      name: 'Chef Sameer Khan',
      role: 'Sous Chef',
      experience: '10 years',
      specialty: 'Mediterranean Grills & Tandoor',
      ability: 'Expert in live-fire cooking — coaxes bold smoky flavors from every cut of meat.',
      photo: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=600&q=80',
    },
    {
      name: 'Chef Lena Rossi',
      role: 'Chef de Partie',
      experience: '8 years',
      specialty: 'Seafood & Coastal Curries',
      ability: 'Brings Kerala coastal heritage to the plate with delicate coconut-based curries.',
      photo: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?auto=format&fit=crop&w=600&q=80',
    },
  ],
  dishes: [
    { name: 'Butter Chicken Royale', category: 'mains', price: 24.99, emoji: '🍗', image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=900&q=80', description: 'Tender chicken in a rich, creamy tomato sauce with aromatic spices.', famousReason: 'Our signature dish since 1998 — featured in Food & Wine magazine.' },
    { name: 'Truffle Biryani', category: 'mains', price: 28.99, emoji: '🍚', image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=900&q=80', description: 'Fragrant basmati rice layered with saffron, spices, and black truffle.', famousReason: 'Winner of the National Culinary Award 2019.' },
    { name: 'Tandoori Lamb Chops', category: 'mains', price: 32.99, emoji: '🥩', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80', description: 'Marinated overnight in yogurt and spices, charred in our clay tandoor.', famousReason: 'Celebrity chef favorite — ordered by 3 Michelin-star chefs.' },
    { name: 'Paneer Tikka Skewers', category: 'starters', price: 14.99, emoji: '🧀', image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=900&q=80', description: 'Cottage cheese cubes grilled with bell peppers and mint chutney.', famousReason: 'Best vegetarian starter in the city — 5 years running.' },
    { name: 'Samosa Chaat', category: 'starters', price: 12.99, emoji: '🥟', image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80', description: 'Crispy samosas topped with yogurt, tamarind, and chutneys.', famousReason: 'Street food elevated — our most Instagrammed dish.' },
    { name: 'Gulab Jamun Cheesecake', category: 'desserts', price: 11.99, emoji: '🍰', image: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=900&q=80', description: 'Fusion dessert blending Indian gulab jamun with New York cheesecake.', famousReason: 'Innovation award winner — only place in the world serving this.' },
    { name: 'Kulfi Falooda', category: 'desserts', price: 9.99, emoji: '🍨', image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=900&q=80', description: 'Traditional Indian ice cream with rose syrup and vermicelli.', famousReason: "Grandmother's recipe passed down four generations." },
    { name: 'Mango Lassi', category: 'drinks', price: 6.99, emoji: '🥭', image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=900&q=80', description: 'Creamy yogurt drink blended with Alphonso mangoes.', famousReason: 'Made with imported Alphonso mangoes — seasonal favorite.' },
    { name: 'Masala Chai', category: 'drinks', price: 4.99, emoji: '☕', image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80', description: 'Spiced tea brewed with cardamom, ginger, and cinnamon.', famousReason: 'Brewed fresh every hour — over 50,000 cups served annually.' },
    { name: 'Seafood Moilee', category: 'mains', price: 29.99, emoji: '🦐', image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=900&q=80', description: 'Kerala-style coconut curry with fresh prawns and fish.', famousReason: "Coastal Kerala recipe — chef's family heritage dish." },
    { name: 'Palak Paneer', category: 'mains', price: 18.99, emoji: '🥬', image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=900&q=80', description: 'Spinach curry with homemade cottage cheese cubes.', famousReason: "Health-conscious diners' top pick for 10 years." },
    { name: 'Rose Sharbat', category: 'drinks', price: 5.99, emoji: '🌹', image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=80', description: 'Refreshing rose-flavored drink with basil seeds.', famousReason: 'Royal Mughal recipe — served at weddings since 1850.' },
  ],
};
